### ISSUE TITLE
Can you explain what Differential Equations -> Deep Learning means and vice versa?

### ISSUE THREAD

**Issue by FabHan** [Zymrael/awesome-neural-ode#4]

**Comment by Zymrael** [comment]
I clarified the meaning by being slightly more verbose. In short, it means `differential equations in deep learning` (either methods or algorithms motivated or inspired by differential equations), while the other direction is dedicated to deep learning in "traditional" differential equations, e.g scientific machine learning, solving differential equations via neural networks.
