### ISSUE TITLE
recommending papers

### ISSUE THREAD

**Issue by jingge326** [Zymrael/awesome-neural-ode#9]
Solving PDEs: 
Fourier Neural Operator for Parametric Partial Differential Equations
Neural Operator: Learning Maps Between Function Spaces

Solving ODEs: 
Neural Flows: Efficient Alternative to Neural ODEs

**Comment by Zymrael** [comment]
Good suggestions, I'd be happy to accept a PR if you're interested. I'll wait a week or two, otherwise I'll add them directly

**Comment by Zymrael** [comment]
Added, thanks for the suggestions!
